apiVersion: skaffold/v2alpha1
kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
    - image: gcr.io/temporal-fx-273605/sologcp
      jib: {}
deploy:
  kubectl:
    manifests:
      - k8s/*.yml