apiVersion: v1
kind: Service
metadata:
  name: gcpdeployment
  labels:
    name: gcpdeployment
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: gcpdeployment
  type: LoadBalancer